[tool.poetry]
name = "wg-easy-api"
version = "2.0.0"
description = "API wrapper for wg-easy v15.4.0"
authors = [
  "AndrewCh <andrey.chikin1223@gmail.com>",
  "d0gied <german.n.u@mail.ru>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/d0gied/wg-easy-api"

[tool.poetry.urls]
"Issues" = "https://github.com/d0gied/wg-easy-api/issues"

[tool.poetry.dependencies]
python = "^3.14"
aiohttp = "^3.14.3"
pydantic = "^2.13.4"
pydantic-settings = "^2.15.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.10"
black = "^24.10.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.2"
pytest-asyncio = "^1.4.0"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
testpaths = ["./tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
